image: node:18.16.0-alpine

default:
  tags:
    - esol-runner

stages:
  - build
  - build-docker-image

build:
  stage: build
  script:
    - npm install
    - npm install -g typescript
    - npm install -g vite
    - npm run build

build-docker-image:
  image: docker:24.0.2
  stage: build-docker-image
  services:
    - docker:dind
  dependencies:
    - build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

